// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyaDUzAx3AVjw9o6qXNCOFNFnfti2ttyw',
    appId: '1:449697263178:web:7ce0114e9020d2742900b3',
    messagingSenderId: '449697263178',
    projectId: 'teleprac',
    authDomain: 'teleprac.firebaseapp.com',
    storageBucket: 'teleprac.appspot.com',
    measurementId: 'G-5EQFRKG0MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA17LWQssJFPgXgnA9GfVHCoYhG49g86Zs',
    appId: '1:449697263178:android:771558f962bb40a02900b3',
    messagingSenderId: '449697263178',
    projectId: 'teleprac',
    storageBucket: 'teleprac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5C0gKai_kJokO6jt36MtjpbEJ6GMfckM',
    appId: '1:449697263178:ios:6d8cbfcf91f1a90f2900b3',
    messagingSenderId: '449697263178',
    projectId: 'teleprac',
    storageBucket: 'teleprac.appspot.com',
    androidClientId: '449697263178-d3dokoukfru0ct3eqivb43ge9opeiahe.apps.googleusercontent.com',
    iosBundleId: 'com.teleprac.teleprac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5C0gKai_kJokO6jt36MtjpbEJ6GMfckM',
    appId: '1:449697263178:ios:6d8cbfcf91f1a90f2900b3',
    messagingSenderId: '449697263178',
    projectId: 'teleprac',
    storageBucket: 'teleprac.appspot.com',
    androidClientId: '449697263178-d3dokoukfru0ct3eqivb43ge9opeiahe.apps.googleusercontent.com',
    iosBundleId: 'com.teleprac.teleprac',
  );
}
